# Generated by Django 5.2.8 on 2025-11-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.CharField(max_length=300, verbose_name='Курс'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completion_id',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
