# Generated by Django 5.2.8 on 2025-11-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись на курс', 'verbose_name_plural': 'Записи на курс'},
        ),
    ]
